Add support for charging weapons
kronosaur/TranscendenceDev pull request #74
Opened 2021-03-27 07:45 UTC by exinfinitum

This PR adds the following:

- `chargeTime` attribute for weapons, which denotes time in frames that a weapon must charge before firing (power and ship counter are consumed, but ammo and weapon capacitor/temperature are not consumed during charging)
- `chargeEffect` and `chargeSound` to denote effect and sound used when charging
- `playSoundOncePerBurst` - if `True`, weapon only plays firing sound on the first shot in a burst
- `onChargeWeapon` effect that functions similarly to `onFireWeapon` but only is fired while the weapon is charging
- `chargeTime`, `fireCharge`, `fireRepeat` and `repeating` fields for `fireEffects` and `chargeEffects` - note that `fireCharge` will be equal to `chargeTime` when weapon is done charging and is actually charging, and `fireRepeat` will be zero when weapon is charging

Note that `onFireWeapon` and other weapon fire events are not triggered when a weapon is charging.

2022-01-13 19:07 UTC, gmoromisato requested changes
Looks pretty good. I made a few local comments; shouldn't take too long to change.

2022-01-13 19:07 UTC, gmoromisato commented on Mammoth/Include/TSEDevices.h
> +			void SetTargetList (CTargetList TargetListArg)
I don't get this change: If you're passing TargetListArg by value, then it will become invalid as soon as SetTargetList goes out of scope. m_pTargetList will point to garbage. [Unless I'm missing something.]

2022-01-13 19:07 UTC, gmoromisato commented on Mammoth/Include/TSEWeaponClassImpl.h
> +						 const bool IsCharging = false);
Consider passing IsCharging as a bool in ActivateCtx instead. That's what it's for: passing options to FireWeapon.

2022-01-13 19:07 UTC, gmoromisato commented on Mammoth/TSE/CWeaponClass.cpp
> +	{
Fix brace indenting (and I apologize again for having unconventional indenting).

2022-01-13 19:07 UTC, gmoromisato commented on Mammoth/TSE/CWeaponClass.cpp
> +	{
Fix indenting

2022-01-13 19:07 UTC, gmoromisato commented on Mammoth/TSE/CWeaponClass.cpp
> +		{
Probably should move this to a function and call it from here. Something like:

if (IsCharging)
   {
   return ChargeWeapon(...)
   }

That will keep FireWeapon cleaner

2022-01-15 06:38 UTC, exinfinitum commented on Mammoth/Include/TSEDevices.h
> +			void SetTargetList (CTargetList TargetListArg)
Seems like this was a mistake that happened when I was updating the PR with the latest master branch. Fixed in latest revision.

2022-01-15 07:45 UTC, exinfinitum commented
This MR should now be ready for review again.

2022-02-02 19:11 UTC, gmoromisato approved these changes

2022-02-03 00:22 UTC, merged